version: '3.9'

networks:
  default:
    name: 'forum'

volumes:
  forum-postgres:
  forum-logs:
  forum-prom:
  forum-grafana:
  forum-os:

services:
  postgres:
    container_name: 'forum-postgres'
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'admin'
    volumes:
      - forum-postgres:/var/lib/postgresql/data

  opensearch:
    image: opensearchproject/opensearch:2.9.0
    container_name: forum-os
    ports:
      - '9200:9200'
      - '9600:9600'
    environment:
      discovery.type: single-node
      plugins.security.disabled: 'true'
    volumes:
      - forum-os:/usr/share/opensearch/data
  
  opensearch-dashboard:
    image: opensearchproject/opensearch-dashboards:2.9.0
    container_name: forum-osd
    ports:
      - "5601:5601"
    environment:
      OPENSEARCH_HOSTS: '["http://forum-os:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: 'true'
    depends_on:
      - opensearch

  prometheus:
    container_name: 'forum-prom'
    image: 'prom/prometheus'
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - forum-prom:/prometheus
  
  loki:
    container_name: 'forum-loki'
    image: 'grafana/loki'
    ports:
      - '3100:3100'
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yml
    command: --config.file=/etc/loki/local-config.yml

  grafana:
    container_name: 'forum-grafana'
    image: 'grafana/grafana'
    restart: unless-stopped
    environment:
      GF_INSTALL_PLUGINS: 'grafana-clock-panel,grafana-simple-json-datasource'
    volumes:
      - forum-grafana:/var/lib/grafana
    ports:
      - '3000:3000'
    depends_on:
      - prometheus
  
  jaeger:
     container_name: 'forum-jaeger'
     image: 'jaegertracing/all-in-one:1.9'
     environment:
       COLLECTOR_ZIPKIN_HOST_PORT: 9411
     ports:
       - '5775:5775/udp'
       - '6831:6831/udp'
       - '6832:6832/udp'
       - '5778:5778'
       - '16686:16686'
       - '14268:14268'
       - '14250:14250'
       - '9411:9411'
  
  api:
    build: 
      context: .
    container_name: 'forum-api'
    ports:
      - 8080:8080
    environment:
      ConnectionStrings__Postgres: 'User ID=postgres;Password=admin;Host=forum-postgres;Port=5432;Database=forum;Pooling=true;MinPoolSize=0;MaxPoolSize=100;Connection Idle Lifetime=60;'
      ConnectionStrings__OpenSearch: 'http://forum-os:9200'
      ConnectionStrings__Tracing: 'http://forum-jaeger:14268/api/traces'
      ConnectionStrings__Loki: 'http://forum-loki:3100'