version: '3.9'

networks:
  default:
    name: 'forum'

volumes:
  forum-postgres:
  forum-logs:
  forum-prom:
  forum-grafana:
  forum-os:

services:
  postgres:
    container_name: 'forum-postgres'
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'ZeroWolf'
    volumes:
      - forum-postgres:/var/lib/postgresql/data

  opensearch:
    image: opensearchproject/opensearch:2.9.0
    container_name: forum-os
    ports:
      - "9200:9200"
      - "9600:9600"
    environment:
      discovery.type: single-node
      plugins.security.disabled: 'true'
    volumes:
      - forum-os:/usr/share/opensearch/data
  
  opensearch-dashboard:
    image: opensearchproject/opensearch-dashboards:2.9.0
    container_name: forum-osd
    ports:
      - "5601:5601"
    environment:
      OPENSEARCH_HOSTS: '["http://forum-os:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: 'true'
    depends_on:
      - opensearch

  prometheus:
    container_name: 'forum-prom'
    image: 'prom/prometheus'
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - forum-prom:/prometheus
  
  grafana:
    container_name: 'forum-grafana'
    image: 'grafana/grafana'
    restart: unless-stopped
    environment:
      GF_INSTALL_PLUGINS: 'grafana-clock-panel,grafana-simple-json-datasource'
    volumes:
      - forum-grafana:/var/lib/grafana
    ports:
      - '3000:3000'
    depends_on:
      - prometheus