scrape_configs:
  - job_name: forum-scrape
    scrape_interval: 10s
    scrape_timeout: 3s
    static_configs:
      - targets:
          - host.docker.internal:5259
        labels:
          app: forum-local
      - targets:
          - forum-api:8080
        labels:
          app: forum-docker
    